### ISSUE TITLE
Corrupted Checkpoint ViT-B-16/Cars/finetuned.pt

### ISSUE THREAD

**Issue by tanganke** [mlfoundations/task_vectors#11]
When I try to load this checkpoint with `torch.load`, it raises

```
RuntimeError: Invalid magic number; corrupt file?
```

The md5sum of download file is `2c3b6a4f39e1b62def9ccf7288099e64`.

**Comment by EnnengYang** [comment]
When using `torch.load(pretrained_checkpoint).state_dict()` fails, you can try `pickle.load(open(pretrained_checkpoint, 'rb')).state_dict()`.

**Comment by tanganke** [comment]
> When using `torch.load(pretrained_checkpoint).state_dict()` fails, you can try `pickle.load(open(pretrained_checkpoint, 'rb')).state_dict()`.

This works. Thanks
