### ISSUE TITLE
Classification Heads for Val Split. 

### ISSUE THREAD

**Issue by prateeky2806** [mlfoundations/task_vectors#3]
Hi @gabrielilharco, I was trying to run some experiments on the validation dataset. I learned from the other issues that I need to use `[dataset]Val` to use the validation split. When trying this the code started to create a head for the validation split of the dataset. Is this the expected behavior? I thought that a single classifier would work for all splits. Am I missing something here?

**Comment by gabrielilharco** [comment]
Hey @prateeky2806. While the code might not be optimized for this, the classification head for all splits should be the same, since the text tower is frozen and the class names do not depend on the split

**Comment by prateeky2806** [comment]
Thank you @gabrielilharco, I am running into another issue when I download the ViT-L-14/Cars/finetuned.pt checkpoint from google drive I am getting an error that the checkpoint is corrupted. All the other checkpoints work fine. I have tried downloading it multiple times and it is still not working. Would it be possible for you to reupload ViT-L-14/Cars/finetuned.pt checkpoint?
