### ISSUE TITLE
Corrupted Checkpoint ViT-L-14/Cars/finetuned.pt

### ISSUE THREAD

**Issue by prateeky2806** [mlfoundations/task_vectors#4]
Hi @gabrielilharco, when I download the ViT-L-14/Cars/finetuned.pt checkpoint from google drive and try to load the checkpoint, I am getting an error that the checkpoint is corrupted. All the other checkpoints work fine. I have tried downloading it multiple times and it is still not working. Would it be possible for you to reupload ViT-L-14/Cars/finetuned.pt checkpoint?

**Comment by gabrielilharco** [comment]
Hey @prateeky2806, I just uploaded a new checkpoint for ViT-L-14 / Cars. Let me know if you're still having problems!

**Comment by prateeky2806** [comment]
Thank you @gabrielilharco, it works now!
