### ISSUE TITLE
Requesting the Multitask Checkpoint For Learning via Addition

### ISSUE THREAD

**Issue by prateeky2806** [mlfoundations/task_vectors#5]
Hi @gabrielilharco, I see that in Appendix D2 you mentioned that you have tried training a multitask checkpoint on the eight vision tasks (SUN397 Cars RESISC45 EuroSAT SVHN GTSRB MNIST DTD) for the learning via addition experiments. I can see that in Appendix D.2 you report the multitask normalized performance to be 99.4. Did you share the raw numbers on each task somewhere? If you can share these checkpoints for ViT-B-32 and ViT-L-14 that would be really helpful.

Thanks in advance,
Prateek

**Comment by gabrielilharco** [comment]
Hey @prateeky2806, here are the raw numbers for both ViT-B-32 and ViT-L-14. I'm including numbers both for fine-tuning for 2k and for 8k steps.

ViT-B-32, 2k steps: `"Cars": 0.6580, "DTD": 0.7809, "EuroSAT": 0.9722, "GTSRB": 0.9732, "MNIST": 0.9902, "RESISC45": 0.9089, "SUN397": 0.6970, "SVHN": 0.9314`
ViT-B-32, 8k steps: `"Cars": 0.7444, "DTD": 0.7787, "EuroSAT": 0.9822, "GTSRB": 0.9891, "MNIST": 0.9945, "RESISC45": 0.9390, "SUN397": 0.7285, "SVHN": 0.9580`

ViT-L-14, 2k steps: `"Cars": 0.8741, "DTD": 0.8415, "EuroSAT": 0.9807, "GTSRB": 0.9875, "MNIST": 0.9935, "RESISC45": 0.9465, "SUN397": 0.7837, "SVHN": 0.9600`
ViT-L-14, 8k steps: `"Cars": 0.9064, "DTD": 0.8436, "EuroSAT": 0.9919, "GTSRB": 0.9907, "MNIST": 0.9963, "RESISC45": 0.9632, "SUN397": 0.8084, "SVHN": 0.9757`

I uploaded the checkpoints here: https://drive.google.com/drive/folders/1TDtlUl8J59MPtvlvK3X39JmNYlMW0Tcz?usp=sharing

**Comment by prateeky2806** [comment]
Thanks @gabrielilharco for the results. 

I tried to download these checkpoints and evaluate them and the files seem to be corrupted (which happened with the Cars checkpoint earlier as well). It seems like there is some sort of corruption happening when you are uploading the files. Can you please reupload these files to Google Drive or if there is some other way you can share them that would be really helpful. 

~~Also, by any chance have you compared task vectors merging with fisher-based merging? I was trying some experiments and the results seem to be pretty bad, way worse than averaging. I was wondering if the classification head needs to be recreated for each merged model separately or if is it independent of the exact checkpoint being used.  As far as I understand the classification head does not depend on the exact checkpoint we are using.~~

Got these to work, I can contribute to the repo at a later point to add [Fisher Merging](https://arxiv.org/abs/2111.09832) and [RegMean](https://openreview.net/forum?id=FCnohuR6AnM). 

Thanks,
Prateek

**Comment by prateeky2806** [comment]
Hi @gabrielilharco, A reminder for requesting the checkpoints. The checkpoints you upload are corrupted. If you please reupload the checkpoint that would be great.

**Comment by prateeky2806** [comment]
After some discussion with the authors, I got it working. Just load the checkpoints using `pickle.load(open('filename', 'rb'))`
